# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.

include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true
    strict-inference: true
  errors:
    missing_return: error
    dead_code: error
    invalid_assignment: warning
    invalid_case_patterns: error
    discarded_futures: error
    noop_primitive_operations: error
    throw_in_finally: error

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    cancel_subscriptions: true
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    prefer_void_to_null: true
    always_put_control_body_on_new_line: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    combinators_ordering: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_constructors_over_static_methods: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
