name: the_puzzle_cell
description: The Puzzle Cell

publish_to: "none"

version: "2.2.0"
gameVersion: "2.2.0.1"

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  base_x: ^2.0.0
  clipboard: any
  cupertino_icons: ^1.0.5
  flame: ^1.4.0
  audioplayers: ^1.1.0
  flame_splash_screen: any
  fluent_ui: ^4.0.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  font_awesome_flutter: any
  http: ^0.13.5
  path: any
  shared_preferences: ^2.0.15
  toml: ^0.13.1
  url_launcher: ^6.1.6
  uuid: any
  web_socket_channel: any
  window_manager: ^0.2.7
  yaml: ^3.1.1
  quiver: ^3.1.0
  archive: ^3.3.1
  file_picker: ^5.2.4
  intl: ^0.17.0
  equatable: ^2.0.5
  lua_vm_bindings:
    git:
      url: https://github.com/IonutParau/lua_vm_bindings
      ref: main
  glue_lang:
    git:
      url: https://github.com/IonutParau/glue_lang
      ref: stable

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/backgrounds/biomes/
    - assets/images/texture_packs/
    - assets/images/mechanical/
    - assets/images/mechanical/gates/
    - assets/images/mechanical/users/
    - assets/images/math/
    - assets/images/math/core/
    - assets/images/math/data/
    - assets/images/math/memory/
    - assets/images/math/functions/
    - assets/images/math/functions/tri/
    - assets/images/math/tunnels/
    - assets/images/math/logic/
    - assets/images/master/
    - assets/images/master/checker/
    - assets/images/master/controller/
    - assets/images/master/getter/
    - assets/images/master/setter/
    - assets/images/skins/
    - assets/images/movers/
    - assets/images/movers/combos/
    - assets/images/movers/movers/
    - assets/images/movers/pullers/
    - assets/images/movers/drillers/
    - assets/images/movers/grabbers/
    - assets/images/movers/speeds/
    - assets/images/backgrounds/
    - assets/images/movers/mirrors/
    - assets/images/rotators/
    - assets/images/push/
    - assets/images/push/restricted/
    - assets/images/push/restricted/Only/
    - assets/images/push/sticky/
    - assets/images/destroyers/
    - assets/images/destroyers/trash/
    - assets/images/destroyers/enemy/
    - assets/images/recreators/
    - assets/images/recreators/fillers/
    - assets/images/recreators/supgens/
    - assets/images/recreators/generators/
    - assets/images/recreators/replicators/
    - assets/images/recreators/tunnels/
    - assets/images/recreators/tunnels/warpers/
    - assets/images/recreators/transformers/
    - assets/images/recreators/forkers/
    - assets/images/recreators/memory/
    - assets/images/puzzle/
    - assets/images/interface/
    - assets/images/interface/tools/
    - assets/images/quantum/
    - assets/images/effects/
    - assets/images/heat/
    - assets/images/unique/
    - assets/images/unique/portal/
    - assets/images/unique/time_travel/
    - assets/images/unique/plant/
    - assets/images/unique/code/
    - assets/audio/
    - languages/
    - mods/
    - mods/testmod/
    - modules/
